set -g fish_color_normal              "{{ colors.on_surface.default.hex }}"
set -g fish_color_command             "{{ colors.primary.default.hex }}"
set -g fish_color_param               "{{ colors.on_surface.default.hex }}"
set -g fish_color_error               "{{ colors.error.default.hex }}"
set -g fish_color_quote               "{{ colors.tertiary.default.hex }}"
set -g fish_color_redirection         "{{ colors.secondary.default.hex }}"
set -g fish_color_end                 "{{ colors.secondary.default.hex }}"
set -g fish_color_option              "{{ colors.tertiary.default.hex }}"
set -g fish_color_operator            "{{ colors.primary.default.hex }}"
set -g fish_color_escape              "{{ colors.tertiary.default.hex }}"
set -g fish_color_cwd                 "{{ colors.primary.default.hex }}"
set -g fish_color_user                "{{ colors.tertiary.default.hex }}"
set -g fish_color_host                "{{ colors.secondary.default.hex }}"
set -g fish_color_autosuggestion      "{{ colors.on_surface_variant.default.hex }}"
set -g fish_color_cancel              "{{ colors.error.default.hex }}"
set -g fish_color_selection           "{{ colors.on_secondary_container.default.hex }}" --background "{{ colors.secondary_container.default.hex }}"
set -g fish_color_search_match        "{{ colors.on_secondary_container.default.hex }}" --background "{{ colors.secondary_container.default.hex }}"

set -g fish_pager_color_prefix                "{{ colors.primary.default.hex }}"
set -g fish_pager_color_completion            "{{ colors.on_surface_variant.default.hex }}"
set -g fish_pager_color_description           "{{ colors.on_surface_variant.default.hex }}"
set -g fish_pager_color_progress              "{{ colors.primary.default.hex }}"
set -g fish_pager_color_secondary_prefix      "{{ colors.secondary.default.hex }}"
set -g fish_pager_color_secondary_completion  "{{ colors.surface_variant.default.hex }}"
set -g fish_pager_color_selected_background   "{{ colors.primary_container.default.hex }}"
set -g fish_pager_color_selected_prefix       "{{ colors.on_primary_container.default.hex }}"
set -g fish_pager_color_selected_completion   "{{ colors.on_primary_container.default.hex }}"
set -g fish_pager_color_selected_description  "{{ colors.on_primary_container.default.hex }}"
