[config]
caching = false

[config.wallpaper]
set = true
command = "awww img --transition-type none {{ image }}"

[templates.kitty]
input_path = "./templates/kitty-colors.conf"
output_path = "~/.cache/tintd/kitty-colors.conf"
post_hook = "pkill -SIGUSR1 kitty || true"

[templates.fish]
input_path = "./templates/fish-colors.fish"
output_path = "~/.cache/tintd/fish-colors.fish"
post_hook = "pkill -SIGUSR1 fish || true"

[templates.hyprland]
input_path = "./templates/hypr-colors.lua"
output_path = "~/.cache/tintd/hypr-colors.lua"
post_hook = "hyprctl reload || true"

[templates.nvim]
input_path = "./templates/nvim-colors.vim"
output_path = "~/.cache/tintd/nvim-colors.vim"
