$mon1 = DP-2
$mon2 = DP-4

workspace=1, monitor:$mon1
workspace=2, monitor:$mon2
workspace=3, monitor:$mon2

exec-once = vesktop
exec-once = spotify

windowrule {
	name = discord-workspace
	match:class = vesktop
	workspace = 2
}

windowrule {
	name = spotify-workspace
	match:class = Spotify
	workspace = 3
}
